### PR TITLE
REFACTOR: fix the headers

### PR DESCRIPTION
**Pull request by amtoine**
ooooook, here we are finally :smirk: 

This PR is focused on fixing the headers of the dotfiles, once and for all :muscle: 

## the new header
as discussed in https://github.com/goatfiles/scripts/pull/36, we will use the following header
```txt
*
*                  _    __ _ _
*   __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
*  / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS:   https://github.com/goatfiles
*  \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
*  |___/
*          MAINTAINERS:
*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
*              ATXR:    https://github.com/atxr    atxr#6214    3B25AF716B608D41AB86C3D20E55E4B1DE5B2C8B
*
```
where each star will follow the comment characters of the file, e.g. `#` in `.py` files and `//` in `c` files

## the method
i edited all the files in this repo, excluding images, with the following command
```bash
hx (
  git lf
  | lines
  | find -v -r "png|jpg|jpeg"
)
```
`hx` being my current editor and `git lf` an alias to `git ls-files`

## the work so far
as you can see, there are two commits in the current branch of the PR:
- 4e39181 removes old and deprecated headers
- 3ee02f5 marks files that could have a header but did not so far

i've made sure there were no conflicts between the two commits with the following script, written in `nushell`:
```bash
def list_files_in_commit [
  commit: string
] {
  git show $commit --stat
  | grep "|"
  | lines
  | str replace "\\s*\\|.*" ""
  | sort
  | uniq
}


let remove = (list_files_in_commit 4e39181)
let add = (list_files_in_commit 3ee02f5)

let all = ($remove | append $add | sort | uniq)

# make sure no file has been modified in both to commits
if ($all | length) != (($remove | length) + ($add | length)) {
  print "some files have been modified in both  '3ee02f5' and '4e39181'..."
} else {
  print "everything's ok"
}
```

## work to be done
of course, the new headers have to be placed in all the files, but now we know which files are concerned :+1: 

## for the time being
@atxr, **could you have a first look at the two commits and see if i broke something?**
i double checked but there could be files:
- where i deleted too much lines, in 4e39181
- that can not have headers, from 3ee02f5
- that i missed... the list of untouched files is coming soon

### CODE REVIEW

**Comment by atxr** [comment]
That's many files! I didn't checked them all one by one, but the huge number of files I reviewed looks correct!

**Comment by amtoine** [comment]
> That's many files!
>
don't know what you are talking about :eyes: 

> I didn't checked them all one by one, but the huge number of files I reviewed looks correct!
>
got it, i'll add the banners soon :+1:

**Review by amtoine — COMMENTED** [review]
i've double checked all the files, looking after
- missing shebangs
- missing external contributors

but could not find any :+1:

**Review by amtoine — COMMENTED** [review]
hey @atxr :wave: 

i've added the banner to all the files
they were 184 before 84d7d1a and they are 184 now again :ok:

i did edit them with `hx $all`, where `$all` is always the same list defined as above :yum: 

i've tried to make sure i use the right comment characters depending on the file type, i can not see any problem on that front for now :thinking: 

## NOTES
i've added a new section to two scripts
```txt
*          CONTRIBUTORS:
*              CIRALA:  https://github.com/cirala/lfimg/blob/master/cleaner
```
in `.config/lf/scripts/cleaner.sh` and
```txt
*          CONTRIBUTORS:
*              CIRALA:  https://github.com/cirala/lfimg/blob/master/preview
```
in `.config/lf/scripts/preview.sh`

**Review by atxr — APPROVED** [review]
I ran the test scripts with success.
I didn't spot any mistake/oversight! :rocket:

**Comment by amtoine** [comment]
coool :relieved: 
hope i did not break anything :laughing: 
we'll see i guess

**Pull request merged**
